services:
  netbootxyz:
    image: netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      VERSION: "latest"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./netbootxyz:/storage
    restart: always
    stop_grace_period: 2m
